
/*
 * 
 */

package com.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1.2
 * Mon Oct 23 15:39:59 CST 2017
 * Generated source version: 2.1.2
 * 
 */


@WebServiceClient(name = "GetInfoServiceImplService", 
                  wsdlLocation = "http://localhost:6080/ssm-crud/ws/getInfoService?wsdl",
                  targetNamespace = "http://impl.service.app.demo.sysware.com/") 
public class GetInfoServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://impl.service.app.demo.sysware.com/", "GetInfoServiceImplService");
    public final static QName GetInfoServiceImplPort = new QName("http://impl.service.app.demo.sysware.com/", "GetInfoServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:6080/ssm-crud/ws/getInfoService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:6080/ssm-crud/ws/getInfoService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public GetInfoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetInfoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetInfoServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns IGetInfoService
     */
    @WebEndpoint(name = "GetInfoServiceImplPort")
    public IGetInfoService getGetInfoServiceImplPort() {
        return super.getPort(GetInfoServiceImplPort, IGetInfoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGetInfoService
     */
    @WebEndpoint(name = "GetInfoServiceImplPort")
    public IGetInfoService getGetInfoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(GetInfoServiceImplPort, IGetInfoService.class, features);
    }

}
