package com.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.2
 * Mon Oct 23 15:39:59 CST 2017
 * Generated source version: 2.1.2
 * 
 */
 
@WebService(targetNamespace = "http://inf.service.app.demo.sysware.com/", name = "IGetInfoService")
@XmlSeeAlso({ObjectFactory.class})
public interface IGetInfoService {

    @RequestWrapper(localName = "addEmployee", targetNamespace = "http://inf.service.app.demo.sysware.com/", className = "com.ws.AddEmployee")
    @ResponseWrapper(localName = "addEmployeeResponse", targetNamespace = "http://inf.service.app.demo.sysware.com/", className = "com.ws.AddEmployeeResponse")
    @WebMethod
    public void addEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        com.ws.Employee arg0
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getRetInfo", targetNamespace = "http://inf.service.app.demo.sysware.com/", className = "com.ws.GetRetInfo")
    @ResponseWrapper(localName = "getRetInfoResponse", targetNamespace = "http://inf.service.app.demo.sysware.com/", className = "com.ws.GetRetInfoResponse")
    @WebMethod
    public com.ws.RetInfo getRetInfo(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "age", targetNamespace = "")
        int age
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://inf.service.app.demo.sysware.com/", className = "com.ws.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://inf.service.app.demo.sysware.com/", className = "com.ws.AddResponse")
    @WebMethod
    public int add(
        @WebParam(name = "num1", targetNamespace = "")
        int num1,
        @WebParam(name = "num2", targetNamespace = "")
        int num2
    );
}
