package com.fol;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.2
 * Wed Nov 15 14:39:17 CST 2017
 * Generated source version: 2.1.2
 * 
 */
 
@WebService(targetNamespace = "http://ws.agent.service.dms.sgm.com/", name = "BonusOperationWebService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BonusOperationWebService {

    @WebResult(name = "tranformFrznBonusFundResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
    @WebMethod
    public TranformFrznBonusFundResponse tranformFrznBonusFund(
        @WebParam(partName = "body", name = "tranformFrznBonusFund", targetNamespace = "http://ws.agent.service.dms.sgm.com/")
        TranformFrznBonusFund body,
        @WebParam(partName = "header", mode = WebParam.Mode.INOUT, name = "SGMCommonHeader", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMCommonHeader/v1", header = true)
        javax.xml.ws.Holder<SGMCommonHeaderType> header
    ) throws SgmErrorFault;

    @WebResult(name = "tranformBonusFundResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
    @WebMethod
    public TranformBonusFundResponse tranformBonusFund(
        @WebParam(partName = "body", name = "tranformBonusFund", targetNamespace = "http://ws.agent.service.dms.sgm.com/")
        TranformBonusFund body,
        @WebParam(partName = "header", mode = WebParam.Mode.INOUT, name = "SGMCommonHeader", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMCommonHeader/v1", header = true)
        javax.xml.ws.Holder<SGMCommonHeaderType> header
    ) throws SgmErrorFault;

    @WebResult(name = "tranformBonusFundCompensationResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
    @WebMethod
    public TranformBonusFundCompensationResponse tranformBonusFundCompensation(
        @WebParam(partName = "body", name = "tranformBonusFundCompensation", targetNamespace = "http://ws.agent.service.dms.sgm.com/")
        TranformBonusFundCompensation body,
        @WebParam(partName = "header", mode = WebParam.Mode.INOUT, name = "SGMCommonHeader", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMCommonHeader/v1", header = true)
        javax.xml.ws.Holder<SGMCommonHeaderType> header
    ) throws SgmErrorFault;

    @WebResult(name = "tranformFrznBonusFundCompensationResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
    @WebMethod
    public TranformFrznBonusFundCompensationResponse tranformFrznBonusFundCompensation(
        @WebParam(partName = "body", name = "tranformFrznBonusFundCompensation", targetNamespace = "http://ws.agent.service.dms.sgm.com/")
        TranformFrznBonusFundCompensation body,
        @WebParam(partName = "header", mode = WebParam.Mode.INOUT, name = "SGMCommonHeader", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMCommonHeader/v1", header = true)
        javax.xml.ws.Holder<SGMCommonHeaderType> header
    ) throws SgmErrorFault;

    @WebResult(name = "tranformUnFrznBonusFundCompensationResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
    @WebMethod
    public TranformUnFrznBonusFundCompensationResponse tranformUnFrznBonusFundCompensation(
        @WebParam(partName = "body", name = "tranformUnFrznBonusFundCompensation", targetNamespace = "http://ws.agent.service.dms.sgm.com/")
        TranformUnFrznBonusFundCompensation body,
        @WebParam(partName = "header", mode = WebParam.Mode.INOUT, name = "SGMCommonHeader", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMCommonHeader/v1", header = true)
        javax.xml.ws.Holder<SGMCommonHeaderType> header
    ) throws SgmErrorFault;

    @WebResult(name = "tranformUnFrznBonusFundResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
    @WebMethod
    public TranformUnFrznBonusFundResponse tranformUnFrznBonusFund(
        @WebParam(partName = "body", name = "tranformUnFrznBonusFund", targetNamespace = "http://ws.agent.service.dms.sgm.com/")
        TranformUnFrznBonusFund body,
        @WebParam(partName = "header", mode = WebParam.Mode.INOUT, name = "SGMCommonHeader", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMCommonHeader/v1", header = true)
        javax.xml.ws.Holder<SGMCommonHeaderType> header
    ) throws SgmErrorFault;
}
