
package com.fol;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.2
 * Wed Nov 15 14:39:17 CST 2017
 * Generated source version: 2.1.2
 * 
 */

@WebFault(name = "SGMError", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMError/v1")
public class SgmErrorFault extends Exception {
    public static final long serialVersionUID = 20171115143917L;
    
    private com.fol.SGMErrorType sgmError;

    public SgmErrorFault() {
        super();
    }
    
    public SgmErrorFault(String message) {
        super(message);
    }
    
    public SgmErrorFault(String message, Throwable cause) {
        super(message, cause);
    }

    public SgmErrorFault(String message, com.fol.SGMErrorType sgmError) {
        super(message);
        this.sgmError = sgmError;
    }

    public SgmErrorFault(String message, com.fol.SGMErrorType sgmError, Throwable cause) {
        super(message, cause);
        this.sgmError = sgmError;
    }

    public com.fol.SGMErrorType getFaultInfo() {
        return this.sgmError;
    }
}
